version: "3"

services:
  counter:
    image: grpctestapp
    command: ["/grpctestapp", "-bindaddr", "0.0.0.0:50051", "server"]
    ports:
      - "50051"
    deploy:
      replicas: 1

  client:
    image: grpctestapp
    command: ["/grpctestapp", "-hostaddr", "counter:50051", "-bindaddr", "0.0.0.0:8080", "client"]
    ports:
      - "8080:8080"
    deploy:
      replicas: 3